---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by WDNMD.
--- DateTime: 2026/4/29 12:23
---
local voucherId = ARGV[1]
local userId = ARGV[2]
local orderId = ARGV[3]


local stockKey = "seckill:stock:" .. voucherId
local orderKey = "seckill:order:" .. voucherId

local stock = tonumber(redis.call('get', stockKey) or "0")

-- 判断库存
if stock <= 0 then
    return 1
end

-- 判断是否重复下单
if redis.call('sismember', orderKey, userId) == 1 then
    return 2
end

-- 扣库存
redis.call('incrby', stockKey, -1)

-- 保存用户
redis.call('sadd', orderKey, userId)

--发送消息到队列当中 XADD stream.orders * k1 v1 k2 v2..
redis.call('xadd','stream.orders','*','userId',userId,'voucherId',voucherId,'id',orderId)
return 0
